# Site settings
title: Li-Battery's website               # 网站的标题
description: "This is my awesome personal website" # 网站的描述
url: "https://li-battery-dc.github.io"  # 网站的 URL，GitHub Pages 会自动处理

# Theme settings
theme: minima                       # 选择主题为 Minima
theme_dir: _themes/minima            # 如果使用自定义的 Minima 主题路径

# Social links (optional)
social_links:
  - name: "email"
    url: "liu-dc23@mails.tsinghua.edu.cn"
  - name: "GitHub"
    url: "https://github.com/Li-Battery-dc"

# Build settings (optional)
markdown: kramdown                 # 使用的Markdown解析器（支持kramdown和redcarpet）
permalink: pretty                  # URL结构，pretty表示美化URL
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
